### ISSUE TITLE
lectura final

### ISSUE THREAD

**Issue by gstvrmrlpz** [geneura-papers/2015-GPUS#12]
se acabó lo que se daba... echadle si podéis un vistazo final y mañana le mando los dos pdfs del directorio final a la china.

**Comment by amorag** [comment]
Estoy con ello ahora mismo. :D

De: gustavo [mailto:notifications@github.com] 
Enviado el: sábado, 18 de junio de 2016 2:26
Para: geneura-papers/2015-GPUS
Asunto: [geneura-papers/2015-GPUS] lectura final (#12)

se acabó lo que se daba... echadle si podéis un vistazo final y mañana le mando los dos pdfs del directorio final a la china.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub https://github.com/geneura-papers/2015-GPUS/issues/12 , or mute the thread https://github.com/notifications/unsubscribe/AC6-Wq_REKG3bf_UHciFOigqZrK5zkilks5qMzsUgaJpZM4I404a .  https://github.com/notifications/beacon/AC6-Wpi_PfNoJJOmrNAJe6-OOVBtIdURks5qMzsUgaJpZM4I404a.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.6201 / Base de datos de virus: 4604/12441 - Fecha de publicación: 06/17/16

**Comment by amorag** [comment]
Hecho.
He tenido que fusionar las versiones por conflictos, pero se ha quedado bien. ;D

Echadle un ojo a lo nuevo a ver si os gusta.
